# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('ipaddress', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='Источник обращения')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='E-mail')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Компания')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
    ]
