# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock())))),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ThisSiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='911', max_length=20, verbose_name='Основной номер телефона')),
                ('email', models.EmailField(default='hello@example.com', max_length=254, verbose_name='Основной email')),
                ('address', models.TextField(default='Moscow, Tolstoy square', verbose_name='Основной адрес')),
                ('from_email', models.EmailField(default='robot@example.com', help_text='Email-адрес с которого приходят письма.', max_length=254, verbose_name='Адрес отправителя')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Основные',
            },
        ),
    ]
